#lOS TIPO DE DATOS MAS COMUNES EN PYTHON SON

#Simples o primitivos
#int(entero)
#float(real)
#bool(logico)

#Estructurados
#str(cadena)
#list(lista)
#tuple
#dict(como un objeto)

#Ejemplos de variables primitivos o simples
entero=23
float=3.1416
logico=false

#Estructurado
palabra="Hola"
palabra2="@"
lista=(10,20,30,40)
lista2(True,10,3.3,,"Que tal","9")
tuple("Hola","que","tal")
dict={
    "nombre":"Daniel",
    "apellido":"Hernandez Homez",
    "edad":20,
    "estatura:1.7"
}

#Mostrar el tipo de dato de cada identificador
print(type(entero))
print(type(float))
print(type(logico))
print(type(palabra))